#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picerija.Upotreba.Liste
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Prodaja")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJedinicaMjere(JedinicaMjere instance);
    partial void UpdateJedinicaMjere(JedinicaMjere instance);
    partial void DeleteJedinicaMjere(JedinicaMjere instance);
    partial void InsertUloge(Uloge instance);
    partial void UpdateUloge(Uloge instance);
    partial void DeleteUloge(Uloge instance);
    partial void InsertKorpa(Korpa instance);
    partial void UpdateKorpa(Korpa instance);
    partial void DeleteKorpa(Korpa instance);
    partial void InsertProizvodi(Proizvodi instance);
    partial void UpdateProizvodi(Proizvodi instance);
    partial void DeleteProizvodi(Proizvodi instance);
    partial void InsertRadnici(Radnici instance);
    partial void UpdateRadnici(Radnici instance);
    partial void DeleteRadnici(Radnici instance);
    partial void InsertStavkeKorpe(StavkeKorpe instance);
    partial void UpdateStavkeKorpe(StavkeKorpe instance);
    partial void DeleteStavkeKorpe(StavkeKorpe instance);
    partial void InsertKategorije(Kategorije instance);
    partial void UpdateKategorije(Kategorije instance);
    partial void DeleteKategorije(Kategorije instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Picerija.Properties.Settings.Default.ProdajaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JedinicaMjere> JedinicaMjeres
		{
			get
			{
				return this.GetTable<JedinicaMjere>();
			}
		}
		
		public System.Data.Linq.Table<Uloge> Uloges
		{
			get
			{
				return this.GetTable<Uloge>();
			}
		}
		
		public System.Data.Linq.Table<Korpa> Korpas
		{
			get
			{
				return this.GetTable<Korpa>();
			}
		}
		
		public System.Data.Linq.Table<Proizvodi> Proizvodis
		{
			get
			{
				return this.GetTable<Proizvodi>();
			}
		}
		
		public System.Data.Linq.Table<Radnici> Radnicis
		{
			get
			{
				return this.GetTable<Radnici>();
			}
		}
		
		public System.Data.Linq.Table<StavkeKorpe> StavkeKorpes
		{
			get
			{
				return this.GetTable<StavkeKorpe>();
			}
		}
		
		public System.Data.Linq.Table<Kategorije> Kategorijes
		{
			get
			{
				return this.GetTable<Kategorije>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vratiListeNaOsnovuId")]
		public ISingleResult<vratiListeNaOsnovuIdResult> vratiListeNaOsnovuId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SifJM", DbType="Int")] System.Nullable<int> sifJM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sifJM);
			return ((ISingleResult<vratiListeNaOsnovuIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vratiPodatkeUloga")]
		public ISingleResult<vratiPodatkeUlogaResult> vratiPodatkeUloga([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUloge", DbType="Int")] System.Nullable<int> idUloge)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUloge);
			return ((ISingleResult<vratiPodatkeUlogaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.kategorijeLista")]
		public ISingleResult<kategorijeListaResult> kategorijeLista([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdKategorije", DbType="Int")] System.Nullable<int> idKategorije)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKategorije);
			return ((ISingleResult<kategorijeListaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JedinicaMjere")]
	public partial class JedinicaMjere : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SifJM;
		
		private string _Naziv;
		
		private EntitySet<Proizvodi> _Proizvodis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSifJMChanging(int value);
    partial void OnSifJMChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    #endregion
		
		public JedinicaMjere()
		{
			this._Proizvodis = new EntitySet<Proizvodi>(new Action<Proizvodi>(this.attach_Proizvodis), new Action<Proizvodi>(this.detach_Proizvodis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifJM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SifJM
		{
			get
			{
				return this._SifJM;
			}
			set
			{
				if ((this._SifJM != value))
				{
					this.OnSifJMChanging(value);
					this.SendPropertyChanging();
					this._SifJM = value;
					this.SendPropertyChanged("SifJM");
					this.OnSifJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JedinicaMjere_Proizvodi", Storage="_Proizvodis", ThisKey="SifJM", OtherKey="SifJM")]
		public EntitySet<Proizvodi> Proizvodis
		{
			get
			{
				return this._Proizvodis;
			}
			set
			{
				this._Proizvodis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Proizvodis(Proizvodi entity)
		{
			this.SendPropertyChanging();
			entity.JedinicaMjere = this;
		}
		
		private void detach_Proizvodis(Proizvodi entity)
		{
			this.SendPropertyChanging();
			entity.JedinicaMjere = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uloge")]
	public partial class Uloge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUloge;
		
		private string _Naziv;
		
		private EntitySet<Radnici> _Radnicis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUlogeChanging(int value);
    partial void OnIdUlogeChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    #endregion
		
		public Uloge()
		{
			this._Radnicis = new EntitySet<Radnici>(new Action<Radnici>(this.attach_Radnicis), new Action<Radnici>(this.detach_Radnicis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUloge", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUloge
		{
			get
			{
				return this._IdUloge;
			}
			set
			{
				if ((this._IdUloge != value))
				{
					this.OnIdUlogeChanging(value);
					this.SendPropertyChanging();
					this._IdUloge = value;
					this.SendPropertyChanged("IdUloge");
					this.OnIdUlogeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uloge_Radnici", Storage="_Radnicis", ThisKey="IdUloge", OtherKey="IdUloge")]
		public EntitySet<Radnici> Radnicis
		{
			get
			{
				return this._Radnicis;
			}
			set
			{
				this._Radnicis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Radnicis(Radnici entity)
		{
			this.SendPropertyChanging();
			entity.Uloge = this;
		}
		
		private void detach_Radnicis(Radnici entity)
		{
			this.SendPropertyChanging();
			entity.Uloge = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Korpa")]
	public partial class Korpa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKorpe;
		
		private System.DateTime _Datum;
		
		private int _IdRadnika;
		
		private EntitySet<StavkeKorpe> _StavkeKorpes;
		
		private EntityRef<Radnici> _Radnici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKorpeChanging(int value);
    partial void OnIdKorpeChanged();
    partial void OnDatumChanging(System.DateTime value);
    partial void OnDatumChanged();
    partial void OnIdRadnikaChanging(int value);
    partial void OnIdRadnikaChanged();
    #endregion
		
		public Korpa()
		{
			this._StavkeKorpes = new EntitySet<StavkeKorpe>(new Action<StavkeKorpe>(this.attach_StavkeKorpes), new Action<StavkeKorpe>(this.detach_StavkeKorpes));
			this._Radnici = default(EntityRef<Radnici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorpe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdKorpe
		{
			get
			{
				return this._IdKorpe;
			}
			set
			{
				if ((this._IdKorpe != value))
				{
					this.OnIdKorpeChanging(value);
					this.SendPropertyChanging();
					this._IdKorpe = value;
					this.SendPropertyChanged("IdKorpe");
					this.OnIdKorpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date NOT NULL")]
		public System.DateTime Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRadnika", DbType="Int NOT NULL")]
		public int IdRadnika
		{
			get
			{
				return this._IdRadnika;
			}
			set
			{
				if ((this._IdRadnika != value))
				{
					if (this._Radnici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRadnikaChanging(value);
					this.SendPropertyChanging();
					this._IdRadnika = value;
					this.SendPropertyChanged("IdRadnika");
					this.OnIdRadnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korpa_StavkeKorpe", Storage="_StavkeKorpes", ThisKey="IdKorpe", OtherKey="IdKorpe")]
		public EntitySet<StavkeKorpe> StavkeKorpes
		{
			get
			{
				return this._StavkeKorpes;
			}
			set
			{
				this._StavkeKorpes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Radnici_Korpa", Storage="_Radnici", ThisKey="IdRadnika", OtherKey="IdRadnika", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Radnici Radnici
		{
			get
			{
				return this._Radnici.Entity;
			}
			set
			{
				Radnici previousValue = this._Radnici.Entity;
				if (((previousValue != value) 
							|| (this._Radnici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Radnici.Entity = null;
						previousValue.Korpas.Remove(this);
					}
					this._Radnici.Entity = value;
					if ((value != null))
					{
						value.Korpas.Add(this);
						this._IdRadnika = value.IdRadnika;
					}
					else
					{
						this._IdRadnika = default(int);
					}
					this.SendPropertyChanged("Radnici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StavkeKorpes(StavkeKorpe entity)
		{
			this.SendPropertyChanging();
			entity.Korpa = this;
		}
		
		private void detach_StavkeKorpes(StavkeKorpe entity)
		{
			this.SendPropertyChanging();
			entity.Korpa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proizvodi")]
	public partial class Proizvodi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProizvoda;
		
		private string _Naziv;
		
		private int _SifJM;
		
		private decimal _Cijena;
		
		private System.Data.Linq.Binary _Slika;
		
		private string _Opis;
		
		private EntitySet<StavkeKorpe> _StavkeKorpes;
		
		private EntityRef<JedinicaMjere> _JedinicaMjere;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProizvodaChanging(int value);
    partial void OnIdProizvodaChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnSifJMChanging(int value);
    partial void OnSifJMChanged();
    partial void OnCijenaChanging(decimal value);
    partial void OnCijenaChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    #endregion
		
		public Proizvodi()
		{
			this._StavkeKorpes = new EntitySet<StavkeKorpe>(new Action<StavkeKorpe>(this.attach_StavkeKorpes), new Action<StavkeKorpe>(this.detach_StavkeKorpes));
			this._JedinicaMjere = default(EntityRef<JedinicaMjere>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProizvoda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdProizvoda
		{
			get
			{
				return this._IdProizvoda;
			}
			set
			{
				if ((this._IdProizvoda != value))
				{
					this.OnIdProizvodaChanging(value);
					this.SendPropertyChanging();
					this._IdProizvoda = value;
					this.SendPropertyChanged("IdProizvoda");
					this.OnIdProizvodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifJM", DbType="Int NOT NULL")]
		public int SifJM
		{
			get
			{
				return this._SifJM;
			}
			set
			{
				if ((this._SifJM != value))
				{
					if (this._JedinicaMjere.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSifJMChanging(value);
					this.SendPropertyChanging();
					this._SifJM = value;
					this.SendPropertyChanged("SifJM");
					this.OnSifJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Decimal(18,2) NOT NULL")]
		public decimal Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(100)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proizvodi_StavkeKorpe", Storage="_StavkeKorpes", ThisKey="IdProizvoda", OtherKey="IdProizvoda")]
		public EntitySet<StavkeKorpe> StavkeKorpes
		{
			get
			{
				return this._StavkeKorpes;
			}
			set
			{
				this._StavkeKorpes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JedinicaMjere_Proizvodi", Storage="_JedinicaMjere", ThisKey="SifJM", OtherKey="SifJM", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public JedinicaMjere JedinicaMjere
		{
			get
			{
				return this._JedinicaMjere.Entity;
			}
			set
			{
				JedinicaMjere previousValue = this._JedinicaMjere.Entity;
				if (((previousValue != value) 
							|| (this._JedinicaMjere.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JedinicaMjere.Entity = null;
						previousValue.Proizvodis.Remove(this);
					}
					this._JedinicaMjere.Entity = value;
					if ((value != null))
					{
						value.Proizvodis.Add(this);
						this._SifJM = value.SifJM;
					}
					else
					{
						this._SifJM = default(int);
					}
					this.SendPropertyChanged("JedinicaMjere");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StavkeKorpes(StavkeKorpe entity)
		{
			this.SendPropertyChanging();
			entity.Proizvodi = this;
		}
		
		private void detach_StavkeKorpes(StavkeKorpe entity)
		{
			this.SendPropertyChanging();
			entity.Proizvodi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Radnici")]
	public partial class Radnici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRadnika;
		
		private string _Prezime;
		
		private string _Ime;
		
		private string _Telefon;
		
		private System.Nullable<System.DateTime> _DatumRodjenja;
		
		private int _IdUloge;
		
		private string _KorIme;
		
		private string _Sifra;
		
		private System.Nullable<System.DateTime> _KreiranDana;
		
		private System.Data.Linq.Binary _Slika;
		
		private string _AdresaStanovanja;
		
		private System.Nullable<decimal> _TrenutnaPlata;
		
		private System.Nullable<decimal> _PocetnaPlata;
		
		private string _Komentar;
		
		private string _Grad;
		
		private EntitySet<Korpa> _Korpas;
		
		private EntityRef<Uloge> _Uloge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRadnikaChanging(int value);
    partial void OnIdRadnikaChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnDatumRodjenjaChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumRodjenjaChanged();
    partial void OnIdUlogeChanging(int value);
    partial void OnIdUlogeChanged();
    partial void OnKorImeChanging(string value);
    partial void OnKorImeChanged();
    partial void OnSifraChanging(string value);
    partial void OnSifraChanged();
    partial void OnKreiranDanaChanging(System.Nullable<System.DateTime> value);
    partial void OnKreiranDanaChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    partial void OnAdresaStanovanjaChanging(string value);
    partial void OnAdresaStanovanjaChanged();
    partial void OnTrenutnaPlataChanging(System.Nullable<decimal> value);
    partial void OnTrenutnaPlataChanged();
    partial void OnPocetnaPlataChanging(System.Nullable<decimal> value);
    partial void OnPocetnaPlataChanged();
    partial void OnKomentarChanging(string value);
    partial void OnKomentarChanged();
    partial void OnGradChanging(string value);
    partial void OnGradChanged();
    #endregion
		
		public Radnici()
		{
			this._Korpas = new EntitySet<Korpa>(new Action<Korpa>(this.attach_Korpas), new Action<Korpa>(this.detach_Korpas));
			this._Uloge = default(EntityRef<Uloge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRadnika", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdRadnika
		{
			get
			{
				return this._IdRadnika;
			}
			set
			{
				if ((this._IdRadnika != value))
				{
					this.OnIdRadnikaChanging(value);
					this.SendPropertyChanging();
					this._IdRadnika = value;
					this.SendPropertyChanged("IdRadnika");
					this.OnIdRadnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumRodjenja", DbType="Date")]
		public System.Nullable<System.DateTime> DatumRodjenja
		{
			get
			{
				return this._DatumRodjenja;
			}
			set
			{
				if ((this._DatumRodjenja != value))
				{
					this.OnDatumRodjenjaChanging(value);
					this.SendPropertyChanging();
					this._DatumRodjenja = value;
					this.SendPropertyChanged("DatumRodjenja");
					this.OnDatumRodjenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUloge", DbType="Int NOT NULL")]
		public int IdUloge
		{
			get
			{
				return this._IdUloge;
			}
			set
			{
				if ((this._IdUloge != value))
				{
					if (this._Uloge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUlogeChanging(value);
					this.SendPropertyChanging();
					this._IdUloge = value;
					this.SendPropertyChanged("IdUloge");
					this.OnIdUlogeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KorIme", DbType="NVarChar(32)")]
		public string KorIme
		{
			get
			{
				return this._KorIme;
			}
			set
			{
				if ((this._KorIme != value))
				{
					this.OnKorImeChanging(value);
					this.SendPropertyChanging();
					this._KorIme = value;
					this.SendPropertyChanged("KorIme");
					this.OnKorImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifra", DbType="NVarChar(32)")]
		public string Sifra
		{
			get
			{
				return this._Sifra;
			}
			set
			{
				if ((this._Sifra != value))
				{
					this.OnSifraChanging(value);
					this.SendPropertyChanging();
					this._Sifra = value;
					this.SendPropertyChanged("Sifra");
					this.OnSifraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KreiranDana", DbType="Date")]
		public System.Nullable<System.DateTime> KreiranDana
		{
			get
			{
				return this._KreiranDana;
			}
			set
			{
				if ((this._KreiranDana != value))
				{
					this.OnKreiranDanaChanging(value);
					this.SendPropertyChanging();
					this._KreiranDana = value;
					this.SendPropertyChanged("KreiranDana");
					this.OnKreiranDanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresaStanovanja", DbType="NVarChar(50)")]
		public string AdresaStanovanja
		{
			get
			{
				return this._AdresaStanovanja;
			}
			set
			{
				if ((this._AdresaStanovanja != value))
				{
					this.OnAdresaStanovanjaChanging(value);
					this.SendPropertyChanging();
					this._AdresaStanovanja = value;
					this.SendPropertyChanged("AdresaStanovanja");
					this.OnAdresaStanovanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrenutnaPlata", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TrenutnaPlata
		{
			get
			{
				return this._TrenutnaPlata;
			}
			set
			{
				if ((this._TrenutnaPlata != value))
				{
					this.OnTrenutnaPlataChanging(value);
					this.SendPropertyChanging();
					this._TrenutnaPlata = value;
					this.SendPropertyChanged("TrenutnaPlata");
					this.OnTrenutnaPlataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PocetnaPlata", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PocetnaPlata
		{
			get
			{
				return this._PocetnaPlata;
			}
			set
			{
				if ((this._PocetnaPlata != value))
				{
					this.OnPocetnaPlataChanging(value);
					this.SendPropertyChanging();
					this._PocetnaPlata = value;
					this.SendPropertyChanged("PocetnaPlata");
					this.OnPocetnaPlataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komentar", DbType="NVarChar(250)")]
		public string Komentar
		{
			get
			{
				return this._Komentar;
			}
			set
			{
				if ((this._Komentar != value))
				{
					this.OnKomentarChanging(value);
					this.SendPropertyChanging();
					this._Komentar = value;
					this.SendPropertyChanged("Komentar");
					this.OnKomentarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grad", DbType="NVarChar(50)")]
		public string Grad
		{
			get
			{
				return this._Grad;
			}
			set
			{
				if ((this._Grad != value))
				{
					this.OnGradChanging(value);
					this.SendPropertyChanging();
					this._Grad = value;
					this.SendPropertyChanged("Grad");
					this.OnGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Radnici_Korpa", Storage="_Korpas", ThisKey="IdRadnika", OtherKey="IdRadnika")]
		public EntitySet<Korpa> Korpas
		{
			get
			{
				return this._Korpas;
			}
			set
			{
				this._Korpas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uloge_Radnici", Storage="_Uloge", ThisKey="IdUloge", OtherKey="IdUloge", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Uloge Uloge
		{
			get
			{
				return this._Uloge.Entity;
			}
			set
			{
				Uloge previousValue = this._Uloge.Entity;
				if (((previousValue != value) 
							|| (this._Uloge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uloge.Entity = null;
						previousValue.Radnicis.Remove(this);
					}
					this._Uloge.Entity = value;
					if ((value != null))
					{
						value.Radnicis.Add(this);
						this._IdUloge = value.IdUloge;
					}
					else
					{
						this._IdUloge = default(int);
					}
					this.SendPropertyChanged("Uloge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Korpas(Korpa entity)
		{
			this.SendPropertyChanging();
			entity.Radnici = this;
		}
		
		private void detach_Korpas(Korpa entity)
		{
			this.SendPropertyChanging();
			entity.Radnici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StavkeKorpe")]
	public partial class StavkeKorpe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdStavkeKorpe;
		
		private int _IdProizvoda;
		
		private int _IdKorpe;
		
		private decimal _Kolicina;
		
		private EntityRef<Korpa> _Korpa;
		
		private EntityRef<Proizvodi> _Proizvodi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdStavkeKorpeChanging(int value);
    partial void OnIdStavkeKorpeChanged();
    partial void OnIdProizvodaChanging(int value);
    partial void OnIdProizvodaChanged();
    partial void OnIdKorpeChanging(int value);
    partial void OnIdKorpeChanged();
    partial void OnKolicinaChanging(decimal value);
    partial void OnKolicinaChanged();
    #endregion
		
		public StavkeKorpe()
		{
			this._Korpa = default(EntityRef<Korpa>);
			this._Proizvodi = default(EntityRef<Proizvodi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStavkeKorpe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdStavkeKorpe
		{
			get
			{
				return this._IdStavkeKorpe;
			}
			set
			{
				if ((this._IdStavkeKorpe != value))
				{
					this.OnIdStavkeKorpeChanging(value);
					this.SendPropertyChanging();
					this._IdStavkeKorpe = value;
					this.SendPropertyChanged("IdStavkeKorpe");
					this.OnIdStavkeKorpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProizvoda", DbType="Int NOT NULL")]
		public int IdProizvoda
		{
			get
			{
				return this._IdProizvoda;
			}
			set
			{
				if ((this._IdProizvoda != value))
				{
					if (this._Proizvodi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProizvodaChanging(value);
					this.SendPropertyChanging();
					this._IdProizvoda = value;
					this.SendPropertyChanged("IdProizvoda");
					this.OnIdProizvodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorpe", DbType="Int NOT NULL")]
		public int IdKorpe
		{
			get
			{
				return this._IdKorpe;
			}
			set
			{
				if ((this._IdKorpe != value))
				{
					if (this._Korpa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorpeChanging(value);
					this.SendPropertyChanging();
					this._IdKorpe = value;
					this.SendPropertyChanged("IdKorpe");
					this.OnIdKorpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Decimal(18,2) NOT NULL")]
		public decimal Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korpa_StavkeKorpe", Storage="_Korpa", ThisKey="IdKorpe", OtherKey="IdKorpe", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Korpa Korpa
		{
			get
			{
				return this._Korpa.Entity;
			}
			set
			{
				Korpa previousValue = this._Korpa.Entity;
				if (((previousValue != value) 
							|| (this._Korpa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korpa.Entity = null;
						previousValue.StavkeKorpes.Remove(this);
					}
					this._Korpa.Entity = value;
					if ((value != null))
					{
						value.StavkeKorpes.Add(this);
						this._IdKorpe = value.IdKorpe;
					}
					else
					{
						this._IdKorpe = default(int);
					}
					this.SendPropertyChanged("Korpa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proizvodi_StavkeKorpe", Storage="_Proizvodi", ThisKey="IdProizvoda", OtherKey="IdProizvoda", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Proizvodi Proizvodi
		{
			get
			{
				return this._Proizvodi.Entity;
			}
			set
			{
				Proizvodi previousValue = this._Proizvodi.Entity;
				if (((previousValue != value) 
							|| (this._Proizvodi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proizvodi.Entity = null;
						previousValue.StavkeKorpes.Remove(this);
					}
					this._Proizvodi.Entity = value;
					if ((value != null))
					{
						value.StavkeKorpes.Add(this);
						this._IdProizvoda = value.IdProizvoda;
					}
					else
					{
						this._IdProizvoda = default(int);
					}
					this.SendPropertyChanged("Proizvodi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategorije")]
	public partial class Kategorije : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKategorije;
		
		private string _NazivKategorije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKategorijeChanging(int value);
    partial void OnIdKategorijeChanged();
    partial void OnNazivKategorijeChanging(string value);
    partial void OnNazivKategorijeChanged();
    #endregion
		
		public Kategorije()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKategorije", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdKategorije
		{
			get
			{
				return this._IdKategorije;
			}
			set
			{
				if ((this._IdKategorije != value))
				{
					this.OnIdKategorijeChanging(value);
					this.SendPropertyChanging();
					this._IdKategorije = value;
					this.SendPropertyChanged("IdKategorije");
					this.OnIdKategorijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivKategorije", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivKategorije
		{
			get
			{
				return this._NazivKategorije;
			}
			set
			{
				if ((this._NazivKategorije != value))
				{
					this.OnNazivKategorijeChanging(value);
					this.SendPropertyChanging();
					this._NazivKategorije = value;
					this.SendPropertyChanged("NazivKategorije");
					this.OnNazivKategorijeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class vratiListeNaOsnovuIdResult
	{
		
		private int _IdProizvoda;
		
		private string _Naziv;
		
		private int _SifJM;
		
		private decimal _Cijena;
		
		private System.Data.Linq.Binary _Slika;
		
		private string _Opis;
		
		public vratiListeNaOsnovuIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProizvoda", DbType="Int NOT NULL")]
		public int IdProizvoda
		{
			get
			{
				return this._IdProizvoda;
			}
			set
			{
				if ((this._IdProizvoda != value))
				{
					this._IdProizvoda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this._Naziv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifJM", DbType="Int NOT NULL")]
		public int SifJM
		{
			get
			{
				return this._SifJM;
			}
			set
			{
				if ((this._SifJM != value))
				{
					this._SifJM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Decimal(18,2) NOT NULL")]
		public decimal Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this._Cijena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image")]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this._Slika = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(100)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this._Opis = value;
				}
			}
		}
	}
	
	public partial class vratiPodatkeUlogaResult
	{
		
		private int _IdUloge;
		
		private string _Naziv;
		
		public vratiPodatkeUlogaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUloge", DbType="Int NOT NULL")]
		public int IdUloge
		{
			get
			{
				return this._IdUloge;
			}
			set
			{
				if ((this._IdUloge != value))
				{
					this._IdUloge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this._Naziv = value;
				}
			}
		}
	}
	
	public partial class kategorijeListaResult
	{
		
		private int _IdKategorije;
		
		private string _NazivKategorije;
		
		public kategorijeListaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKategorije", DbType="Int NOT NULL")]
		public int IdKategorije
		{
			get
			{
				return this._IdKategorije;
			}
			set
			{
				if ((this._IdKategorije != value))
				{
					this._IdKategorije = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivKategorije", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivKategorije
		{
			get
			{
				return this._NazivKategorije;
			}
			set
			{
				if ((this._NazivKategorije != value))
				{
					this._NazivKategorije = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
